### PR TITLE
Fix stopping of a non-existent OpenSeeFace server

### PR DESCRIPTION
**Pull request by 20kdc**
Basically, none of the settings worked, leading to an inability to properly configure OpenSeeFace for my system (especially due to Python and onnxruntime-related issues I personally have)
Note the results here are still troublesome (the duck's neck does a rather odd turn compared to the last release build) but it's something at least

### CODE REVIEW

**Comment by 20kdc** [comment]
I attempted to resolve the conflicts but ran into issues as master vpuppr is not runnable, with the error "Parser Error: The identifier "Result" isn't a valid type (not a script or class), or couldn't be found on base "self"."

**Comment by you-win** [comment]
Hi sorry for not checking in on your PR (thanks for submitting a PR btw!).

The readme is still being rewritten but in order to develop vpuppr, a custom Godot build is needed. [I provide precompiled binaries on my custom fork.](https://github.com/you-win/godot/releases/tag/3.x-binaries) You can also compile it yourself if random, precompiled binaries are too risky.

Regarding the actual contents of the PR, the OpenSeeFace UI elements have been connected to config values on `master`. The issue of fixing the server being stopped while it's still running still exists (I think), so this PR might still be valid.

Adding new global classes is discouraged, and I'm actually trying to consolidate global classes in the `master` branch as well.

**Comment by 20kdc** [comment]
I've stripped the PR to not include the redundant components.

**Comment by you-win** [comment]
Thanks for the PR!

**Pull request merged**
