### PR TITLE
Add "Download on Flathub" to the README

### PR DESCRIPTION
**Pull request by orowith2os**

### CODE REVIEW

**Comment by you-win** [comment]
Is there a badge there matches the style of the pre-existing Discord badge?

**Comment by orowith2os** [comment]
I don't believe there is, but I can modify the image to your liking if you want

**Comment by you-win** [comment]
If there's no way around it, then it's fine. It's just that the button looks pretty big at the top of the readme IMO

**Comment by orowith2os** [comment]
Maybe there could be a second small badge to show some extra information next to the Discord badge, so it hopefully fits in a bit better

**Comment by orowith2os** [comment]
I'll close this, and instead make a similar PR that contains a rework of the README.

**Pull request closed without merging**
